"""
pdf_generator.py – Generate styled PDF summaries for MediSum.

Uses FPDF2 to produce a professional medical report PDF
containing patient info and the AI-generated structured summary.
"""

import io
import re
from datetime import datetime
from fpdf import FPDF, XPos, YPos


# ── Constants ────────────────────────────────────────────────────────────────

PRIMARY_COLOR   = (15,  82, 111)   # Dark teal
ACCENT_COLOR    = (0,  172, 193)   # Cyan accent
LIGHT_BG        = (235, 248, 252)  # Very light blue tint
TEXT_DARK       = (30,  30,  50)   # Near-black
TEXT_MUTED      = (100, 110, 130)  # Grey
WHITE           = (255, 255, 255)
DIVIDER_COLOR   = (200, 220, 230)


# ── PDF Class ────────────────────────────────────────────────────────────────

class MediSumPDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def __init__(self, patient_name: str = ""):
        super().__init__()
        self.patient_name = patient_name
        self.set_auto_page_break(auto=True, margin=20)

    # ── Header ────────────────────────────────────────────────
    def header(self):
        # Background bar
        self.set_fill_color(*PRIMARY_COLOR)
        self.rect(0, 0, 210, 18, style="F")

        # Logo text
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*WHITE)
        self.set_xy(10, 4)
        self.cell(0, 10, "🏥  MediSum – AI Medical Report Summary", align="L")

        # Page number in header
        self.set_font("Helvetica", "", 8)
        self.set_xy(0, 4)
        self.cell(200, 10, f"Page {self.page_no()}", align="R")

        self.ln(14)

    # ── Footer ────────────────────────────────────────────────
    def footer(self):
        self.set_y(-12)
        self.set_draw_color(*DIVIDER_COLOR)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(1)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*TEXT_MUTED)
        self.cell(0, 5, "Generated by MediSum AI  •  For clinical reference only. Not a substitute for professional medical advice.", align="C")


# ── Helpers ──────────────────────────────────────────────────────────────────

def _clean_markdown(text: str) -> str:
    """Strip markdown bold/italic markers for plain-text PDF rendering."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # **bold**
    text = re.sub(r"\*(.+?)\*",     r"\1", text)    # *italic*
    text = re.sub(r"#{1,6}\s*",     "",    text)    # # headings
    text = re.sub(r"`(.+?)`",       r"\1", text)    # `code`
    return text.strip()


def _section_header(pdf: MediSumPDF, title: str) -> None:
    """Render a coloured section header bar."""
    pdf.set_fill_color(*ACCENT_COLOR)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, f"  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
    pdf.set_text_color(*TEXT_DARK)
    pdf.ln(1)


def _body_text(pdf: MediSumPDF, text: str) -> None:
    """Render body paragraph text."""
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*TEXT_DARK)
    pdf.multi_cell(0, 5, _clean_markdown(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)


# ── Public API ───────────────────────────────────────────────────────────────

def create_summary_pdf(patient_info: dict, summary_text: str) -> bytes:
    """
    Build a styled medical report PDF.

    Args:
        patient_info: dict with keys: name, age, gender, blood_group,
                      contact, patient_id, report_types (list[str])
        summary_text: The AI-generated structured summary string.

    Returns:
        bytes: Raw PDF file content.
    """
    pdf = MediSumPDF(patient_name=patient_info.get("name", "Unknown"))
    pdf.add_page()

    # ── Patient Info Card ────────────────────────────────────
    pdf.set_fill_color(*LIGHT_BG)
    pdf.rect(10, pdf.get_y(), 190, 32, style="F")

    pdf.set_xy(12, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*PRIMARY_COLOR)
    pdf.cell(0, 7, patient_info.get("name", "Unknown Patient"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_x(12)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*TEXT_MUTED)

    age     = patient_info.get("age", "—")
    gender  = patient_info.get("gender", "—")
    blood   = patient_info.get("blood_group", "—")
    contact = patient_info.get("contact", "—")
    pid     = patient_info.get("patient_id", "—")
    rpts    = ", ".join(patient_info.get("report_types", [])) or "—"
    ts      = datetime.now().strftime("%d %b %Y, %H:%M")

    info_line = (
        f"Patient ID: {pid}   |   Age: {age}   |   Gender: {gender}   "
        f"|   Blood Group: {blood}   |   Contact: {contact}"
    )
    pdf.cell(0, 5, info_line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_x(12)
    pdf.cell(0, 5, f"Report Types: {rpts}   |   Generated: {ts}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)

    # ── Summary Sections ─────────────────────────────────────
    # Try to split by known section headers; fall back to full text
    section_markers = [
        "Patient Details",
        "Medical History",
        "Symptoms and Diagnosis",
        "Treatment and Recommendations",
        "Lab Reports",
        "Current Status",
    ]

    # Build a map of section_name → content
    sections: dict[str, str] = {}
    remaining = summary_text

    for i, marker in enumerate(section_markers):
        # Look for the marker (case-insensitive, possibly with * or # prefix)
        pattern = re.compile(
            r"(?:\*{1,2}|#{1,3})?\s*" + re.escape(marker) + r"[:\*]*\s*",
            re.IGNORECASE,
        )
        match = pattern.search(remaining)
        if not match:
            continue
        before = remaining[: match.start()].strip()
        after  = remaining[match.end() :].strip()

        # Find where the next section starts
        next_match = None
        for next_marker in section_markers[i + 1 :]:
            np = re.compile(
                r"(?:\*{1,2}|#{1,3})?\s*" + re.escape(next_marker) + r"[:\*]*\s*",
                re.IGNORECASE,
            )
            nm = np.search(after)
            if nm:
                next_match = nm
                break

        if next_match:
            sections[marker] = after[: next_match.start()].strip()
            remaining = after[next_match.start() :]
        else:
            sections[marker] = after.strip()
            remaining = ""

    if sections:
        for section_name in section_markers:
            content = sections.get(section_name, "").strip()
            if not content:
                continue
            _section_header(pdf, section_name)
            _body_text(pdf, content)
    else:
        # Fallback: render the whole summary as-is
        _section_header(pdf, "AI-Generated Summary")
        _body_text(pdf, summary_text)

    # ── Disclaimer ───────────────────────────────────────────
    pdf.set_fill_color(255, 243, 205)  # Light yellow
    pdf.set_draw_color(255, 193, 7)
    pdf.set_line_width(0.5)
    pdf.set_xy(10, pdf.get_y())
    pdf.rect(10, pdf.get_y(), 190, 12, style="FD")
    pdf.set_xy(13, pdf.get_y() + 2)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(120, 80, 0)
    pdf.multi_cell(
        184, 4,
        "⚠  DISCLAIMER: This summary is AI-generated from uploaded documents for informational purposes only. "
        "It does not constitute a medical diagnosis or professional advice. Always consult a qualified healthcare provider.",
    )

    return bytes(pdf.output())
